name: CI for FastAPI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest requests

    - name: Install Homebrew
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Install Allure CLI
      run: |
        brew install allure
        allure --version

    - name: Wait for MongoDB to be healthy
      run: |
        echo "Waiting for MongoDB..."
        sleep 15

    - name: Start FastAPI server
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 &
      env:
        MONGO_URI: mongodb://localhost:27017
        DB_NAME: ecommerce

    - name: Wait for FastAPI to be ready
      run: |
        echo "Waiting for FastAPI server..."
        sleep 10

    - name: Run API tests and collect Allure results
      env:
        MONGO_URI: mongodb://localhost:27017
        DB_NAME: ecommerce
      run: |
        pytest tests/ --alluredir=allure-results

    - name: Generate Allure HTML report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report